#
POST http://localhost:3000/api/users/
Content-Type:application/json

{
    "name":"Dao Ngoc Ban",
    "email":"csdl@gmail.com",
    "password":"123456"
}


#
GET http://localhost:3000/api/users/
Authorization: